Migrate
trufi-association/trufi-server pull request #2
Opened 2022-04-15 19:36 UTC by SamuelRioTz

@ValorNaram here is the migration changes regarding to the next image
![trufi-server-architecture](https://user-images.githubusercontent.com/43000324/163624463-acf81de0-e8d6-4b54-ba3e-6c21cffe5f33.png)

2022-04-15 21:19 UTC, ValorNaram requested changes

2022-04-15 21:19 UTC, ValorNaram commented on otp/1.5.0/Dockerfile
> +ADD ./otp-1.5.0-shaded.jar .
I would like to add `ADD ./run.sh .` containing the run configuration necessary to run this otp. Probably it's better to use [cmd](https://docs.docker.com/engine/reference/builder/#cmd) and or [entrypoint](https://docs.docker.com/engine/reference/builder/#entrypoint) sentence of a Dockerfile as it is more elegant than using environment variables to give complete command instructions. It works but it is not pretty. The content of environment variable should be kept as easy as possible. This is also a way to prevent potential parsing errors (not occurred during tests).

2022-04-15 21:19 UTC, ValorNaram commented on otp/1.5.0/config.env
> +command="java -Xmx2G -jar otp-1.5.0-shaded.jar --autoReload --autoScan --basePath graphs --graphs graphs --server"
move `command` inside dockerfile

2022-04-15 21:19 UTC, ValorNaram commented on otp/2.0.0/config.env
> +command="java -Xmx2G -jar otp-2.0.0-shaded.jar --load ./graphs"
move command inside dockerfile

2022-04-15 21:19 UTC, ValorNaram commented on otp/2.0.0/Dockerfile
> +ADD ./otp-2.0.0-shaded.jar .
I would like to add ADD ./run.sh . containing the run configuration necessary to run this otp. Probably it's better to use [cmd](https://docs.docker.com/engine/reference/builder/#cmd) and or [entrypoint](https://docs.docker.com/engine/reference/builder/#entrypoint) sentence of a Dockerfile as it is more elegant than using environment variables to give complete command instructions. It works but it is not pretty. The content of environment variable should be kept as easy as possible. This is also a way to prevent potential parsing errors (not occurred during tests).

2022-04-15 21:19 UTC, ValorNaram commented on otp/docker-compose.yml
> +    command: $command
remove this after moving it to dockerfile

2022-04-15 21:19 UTC, ValorNaram commented on otp/2.0.0/config.env
> +command="java -Xmx2G -jar otp-2.0.0-shaded.jar --load ./graphs"
We should also prevent having multiple `config.env` file. My search results show them two files with the same name. 
![Untitled](https://user-images.githubusercontent.com/19347636/163632651-182a5b4a-04f3-44ac-b2a6-7c31554b3f6f.png)
s

Better to put the `config.env` globally under the `otp` folder in general. This also saves typing:

```sh
docker-compose --env-file=config.env up
```

is shorter, cleaner and better than

```sh
docker-compose --env-file="2.0.0/config.env" up
```

2022-04-15 21:19 UTC, ValorNaram commented on otp/1.5.0/config.env
> +command="java -Xmx2G -jar otp-1.5.0-shaded.jar --autoReload --autoScan --basePath graphs --graphs graphs --server"
We should also prevent having multiple `config.env` file. My search results show them two files with the same name. 
![Untitled](https://user-images.githubusercontent.com/19347636/163632651-182a5b4a-04f3-44ac-b2a6-7c31554b3f6f.png)
s

Better to put the `config.env` globally under the `otp` folder in general. This also saves typing:

```sh
docker-compose --env-file=config.env up
```

is shorter, cleaner and better than

```sh
docker-compose --env-file="2.0.0/config.env" up
```

2022-04-15 21:22 UTC, SamuelRioTz commented on otp/1.5.0/Dockerfile
> +ADD ./otp-1.5.0-shaded.jar .
the problem is, all time when I need to adjust the params I need to rebuild the docker image, so the comando should be outside of the docker image

2022-04-15 21:24 UTC, SamuelRioTz commented on otp/1.5.0/config.env
> +command="java -Xmx2G -jar otp-1.5.0-shaded.jar --autoReload --autoScan --basePath graphs --graphs graphs --server"
ok, but how we can choose which version/command want to use?

2022-04-15 21:31 UTC, ValorNaram requested changes

2022-04-15 21:31 UTC, ValorNaram commented on otp/1.5.0/Dockerfile
> +ADD ./otp-1.5.0-shaded.jar .
Well rebuilding docker image with docker-compose is really easy

`docker-compose up --build`

which rebuilds the image if necessary too (beside the compose configuration that up is doing).

Docker itself makes heavily use of caching of command results. Each sentence in a dockerfile receives its own step and cache as you can see

```
Creating network "trufi-server" with the default driver
Building otp
Step 1/4 : FROM openjdk:11-jre
 ---> 3daa11a85983
Step 2/4 : WORKDIR /app
 ---> Running in b049df9a0678
Removing intermediate container b049df9a0678
 ---> dcc20083f888
Step 3/4 : ADD ./otp-2.0.0-shaded.jar .
 ---> b96eef25e701
Step 4/4 : EXPOSE 8080 8081
 ---> Running in b189e964a29d
Removing intermediate container b189e964a29d
 ---> fd5eba4a24a9
```

2022-04-16 07:15 UTC, ValorNaram approved these changes

2022-04-16 07:15 UTC, merged